
<?php if ($userSettingsSaved) : ?>
<p style="font-size: 1.3em; background: #00AB00; color: #FFF; text-align: center; line-height: 200%;">
    Les paramètres ont été enregistrés.</p>
<?php endif;?>
<div class="user-settings-container">

    <div class="block user-settings-notification">
        <h2 class="block-title">Configuration des systèmes d'alerte</h2>
        <div class="block-content">
            <table class="user-notifications">
                <thead>
                    <tr class="user-notifications-header">
                        <th class="user-notifications-type">Service</th>
                        <th class="user-notifications-cost">Coût / Limitation</th>
                        <th class="user-notifications-active">Actif</th>
                        <th class="user-notifications-action">&nbsp;</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($data_notifications AS $name => $notification) : ?>
                        <?php if (empty($notification["label"])) continue; ?>
                    <tr>
                        <td class="user-notifications-type">
                            <?php echo htmlspecialchars($notification["label"]); ?>
                            <?php if (!empty($notification["link"])) : ?>
                            <a class="user-notifications-link"
                                href="<?php echo $notification["link"]; ?>"
                                title="Plus d'informations sur <?php echo $notification["link"]; ?> (nouvelle fenêtre)"
                                target="_blank"><span class="fa fa-info-circle fa-fw"></span></a>
                            <?php endif; ?>
                        </td>
                        <td class="user-notifications-cost">
                            <?php if (empty($notification["cost"])) : ?>
                            Gratuit
                            <?php else: ?>
                            <?php echo htmlspecialchars($notification["cost"]); ?>
                            <?php endif; ?>
                        </td>
                        <td class="user-notifications-active">
                            <span class="fa fa-<?php
                            echo $notification["enabled"] ? "check active" : "minus";
                            ?>"></span>
                        </td>
                        <td class="user-notifications-action">
                            <?php if ($notification["enabled"]) : ?>
                            <a href="?mod=user&amp;a=settings-<?php echo $name; ?>">Configurer</a> |
                            <a href="?mod=user&amp;a=settings-disable-notification&amp;s=<?php echo $name; ?>">Désactiver</a>
                            <?php else: ?>
                            <a href="?mod=user&amp;a=settings-<?php echo $name; ?>">Activer</a>
                            <?php endif; ?>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>

    <div class="block user-settings-apikey">
        <h2 class="block-title">Accès API</h2>
        <div class="block-content">
            <p>
                Cette clé vous permet d'interagir avec votre compte
                LBCAlerte à partir d'autre application.
            </p>
            <form action="" method="post" autocomplete="off"
                onsubmit="return window.confirm('Êtes-vous sur de vouloir réinitialiser la clé ?');">
                <dl>
                    <dd>
                        <input type="text" id="api_key" value="<?php
                            echo htmlspecialchars($form_values["api_key"]);
                        ?>" readonly="readonly" />
                    </dd>
                </dl>

                <p>
                    Si nécessaire, vous pouvez réinitialiser votre clé.
                    Il faudra configurer la nouvelle clé dans vos applications.
                </p>
                <p><input type="submit" name="regenerate-apikey"
                    value="Régénérer" /></p>
            </form>
        </div>
    </div>

    <div class="block user-settings-general">
        <h2 class="block-title">Options diverses</h2>
        <div class="block-content">
            <form action="" method="post" autocomplete="off">
                <dl>
                    <dt style="margin-bottom: 10px;">
                        <input type="hidden" name="unique_ads" value="0" />
                        <label for="unique_ads">
                            <input type="checkbox" id="unique_ads" name="unique_ads" value="1"<?php
                                echo $params["unique_ads"] ?' checked="checked"':''
                            ?> style="margin-left: 0;" />
                            Cochez la case pour ne pas recevoir les annonces remontées (évite les doublons).
                        </label>
                    </dt>
                </dl>

                <p><input type="submit" value="Enregistrer" /></p>
            </form>
        </div>
    </div>
</div>