<form action="" method="post" autocomplete="off">
    <?php if (!empty($errorsTest)) : ?>
    <p class="error big">
        Le test d'envoi a échoué :<br />
        <?php echo htmlspecialchars($errorsTest); ?>
    </p>
    <?php elseif (empty($errors) && !empty($_POST["test-config"])) : ?>
    <p class="message-success">
        Vous devriez recevoir une notification contenant le message suivant:
        «&nbsp;La notification Pushover est fonctionnelle&nbsp;».<br />
        <span style="text-decoration: underline;">Pensez à confirmer
        la configuration en cliquant sur "Enregistrer".</span>
    </p>
    <?php endif;?>

    <h2>Configuration de Pushover</h2>
    <dl>
        <dt>
            <label for="token">Clé application</label>
        </dt>
        <dd>
            <input type="text" id="token" name="token" value="<?php
                echo htmlspecialchars($form_values["token"]);
            ?>" />
            <?php if (isset($errors["token"])) : ?>
            <p class="error"><?php echo $errors["token"]; ?></p>
            <?php endif; ?>
        </dd>
        <dt>
            <label for="user_key">Clé utilisateur</label>
        </dt>
        <dd>
            <input type="text" id="user_key" name="user_key" value="<?php
                echo htmlspecialchars($form_values["user_key"]);
            ?>" />
            <?php if (isset($errors["user_key"])) : ?>
            <p class="error"><?php echo $errors["user_key"]; ?></p>
            <?php endif; ?>
        </dd>
    </dl>

    <p>
        <input type="submit" name="test-config" value="Effectuer un test d'envoi" />
        <input type="submit" value="Enregistrer" />
        <?php if ($data_user) : ?>
        <input type="submit" name="delete-config" value="Supprimer la configuration" />
        <?php endif; ?>
        <input type="submit" name="cancel-config" value="Annuler" />
    </p>
</form>
