<form action="" method="post" style="width: 600px;">
    <fieldset>
        <legend>Génération d'un flux RSS</legend>
        <dl>
            <dt><label for="url">
                Indiquer l'adresse de recherche Leboncoin</label></dt>
            <dd><input type="text" id="url" name="url" value="<?php
                echo $values["url"]; ?>" size="75" /></dd>
            <dt>
                <label>Filtre sur le prix</label>
            <dt>
            <dd>
                <label for="price_min">
                    Prix min :
                    <input type="text" id="price_min" name="price_min" value="<?php
                        echo $values["price_min"]; ?>" size="6" />
                </label>
                <label for="price_max">
                    Prix max :
                    <input type="text" id="price_max" name="price_max" value="<?php
                        echo $values["price_max"]; ?>" size="6" />
                </label>
                <?php if (isset($errors["price"])) : ?>
                <p class="error"><?php echo $errors["price"]; ?></p>
                <?php endif; ?>
                <br />
                <label for="price_strict"><input type="checkbox"
                    id="price_strict" name="price_strict" value="1"<?php
                    echo $values["price_strict"]?' checked="checked"':"";
                ?> /> cochez cette case pour exclure les annonces sans prix d'indiqué de votre recherche.</label>
            </dd>
            <dt><label for="cities">Filtre sur les villes (une par ligne)</label></dt>
            <dd>
                <textarea id="cities" name="cities" cols="30" rows="10"><?php
                    echo htmlspecialchars($values["cities"]) ?></textarea>
            </dd>
            <dt><label>Filtre multi-catégorie</label></dt>
            <dd style="overflow: auto; height: 150px;">
                <?php foreach ($categoryCollection->fetchAll() AS $group => $categories) : ?>
                <?php echo htmlspecialchars($group); ?><br />
                <?php foreach ($categories AS $id => $category) : ?>
                <label for="category-<?php echo $id; ?>"><input id="category-<?php
                    echo $id; ?>" type="checkbox" name="categories[]" value="<?php
                    echo htmlspecialchars($category); ?>" /><?php
                    echo htmlspecialchars($category); ?></label><br />
                <?php endforeach; ?>
                <?php endforeach; ?>
            </dd>
            <dt>&nbsp;</dt>
            <dd><input type="submit" value="Générer le flux" /></dd>
        </dl>
    </fieldset>
</form>