<?php if (isset($_POST["testProxy"])) : ?>
<div style="width: 680px; border: 1px solid #666666; margin-bottom: 10px; padding: 10px;">
    <h2>Test de connexion</h2>
    <ul>
        <?php if (!$connector->hasProxy()) : ?>
        <li>aucun proxy configuré.</li>
        <?php else: ?>
        <li>utilisation d'un proxy pour la connexion.</li>
        <?php endif; ?>
        <li>Connexion à <a href="http://portail.free.fr">portail.free.fr</a> :
            <?php if (isset($errors["test"]["site"])) : ?>
            <span style="color: red;">échec</span>
            (erreur: <?php echo htmlspecialchars($errors["test"]["site"]); ?>)
            <?php else: ?>
            <span style="color: #009900;">réussi</span>
            <?php endif; ?>
        </li>
        <li>Connexion à <a href="https://www.leboncoin.fr">Leboncoin</a> :
            <?php if (isset($errors["test"]["lbc"])) : ?>
            <span style="color: red;">échec</span>
            (erreur: <?php echo htmlspecialchars($errors["test"]["lbc"]); ?>)
            <?php else: ?>
            <span style="color: #009900;">réussi</span>
            <?php endif; ?>
        </li>
    </ul>
</div>
<?php endif; ?>
<h2>Configuration d'un serveur proxy</h2>
<p>
    Vous pouvez configurer ici un proxy de connexion qui sera
    utilisé pour se connecter à Leboncoin.
</p>
<form action="" method="post" autocomplete="off">
    <h2>Paramètres du proxy</h2>
    <dl>
        <dt><label for="proxy_ip">Adresse du proxy</label></dt>
        <dd><input type="text" id="proxy_ip" name="proxy_ip" value="<?php
                echo htmlspecialchars($options["proxy_ip"]);
            ?>" /></dd>
        <dt><label for="proxy_port">Port</label></dt>
        <dd><input type="text" id="proxy_port" name="proxy_port" value="<?php
                echo htmlspecialchars($options["proxy_port"]);
            ?>" size="7" /></dd>
    </dl>

    <h2>Le serveur proxy requiert une identification ?</h2>
    <dl>
        <dt><label for="proxy_user">Utilisateur</label></dt>
        <dd><input type="text" id="proxy_user" name="proxy_user" value="<?php
                echo htmlspecialchars($options["proxy_user"]);
            ?>" />
        </dd>
        <dt><label for="proxy_password">Mot de passe</label></dt>
        <dd><input type="password" id="proxy_password" name="proxy_password"<?php
            echo !empty($options["proxy_password"])?' placeholder="Valeur masquée"':""; ?> /></dd>
    </dl>
    <p>
        <input type="submit" value="Enregistrer" />
        <input type="submit" name="testProxy" value="Tester la connexion" />
    </p>
</form>
