<p><a href="?mod=admin&amp;a=add-user">Nouvel utilisateur</a></p>
<table style="width: 500px; text-align: left;">
    <thead>
        <tr>
            <th>Nom d'utilisateur</th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($users AS $user) : ?>
        <tr>
            <td><?php echo htmlspecialchars($user->getUsername()); ?></td>
            <td>
                <a href="?mod=admin&amp;a=password-user&amp;username=<?php echo urlencode($user->getUsername()); ?>">modifier le mot de passe</a>
                <?php if (!$user->isAdmin()) : ?>
                | <a href="?mod=admin&amp;a=delete-user&amp;username=<?php echo urlencode($user->getUsername()); ?>">supprimer</a>
                <?php endif; ?>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>