<?php ob_start(); ?>
<div>
    <?php if ($ad->getDate()) : ?>
    <strong>Publié le <?php echo date("d/m/Y à H:i", $ad->getDate()); ?></strong>
    <?php if (!empty($baseurl) && isset($config) && $config->getOption("allow_backup")) : ?>
    - <a href="<?php echo $baseurl; ?>?mod=annonce&amp;a=backup&amp;aurl=<?php echo $ad->getLink(); ?>"
        target="_blank">Sauvegarder</a>
    <?php endif; ?>
    <br />
    <?php endif; ?>

    <strong>Nom</strong> :
         <a href="<?php echo $ad->getLink(); ?>"><?php echo $ad->getTitle(); ?></a>
         <?php if ($link_mobile = $ad->getLinkMobile()) : ?>
        (<a href="<?php echo $link_mobile; ?>">Version Mobile</a>)
        <?php endif; ?>
    <?php if ($ad->getPrice()) : ?>
    &nbsp;&nbsp;&nbsp;&nbsp;<strong>Prix</strong> : <?php echo number_format($ad->getPrice(), 0, ',', ' '); ?> <?php echo $ad->getCurrency(); ?>
    <?php endif; ?>

    <?php if ($ad->getCategory()) : ?>
    <br />
    <strong>Catégorie</strong> : <?php echo $ad->getCategory(); ?>
    <?php endif; ?>
    <br />
    <?php if ($ad->getCountry()) : ?>
    <strong>Département</strong> : <?php echo $ad->getCountry(); ?>
    &nbsp;&nbsp;&nbsp;&nbsp;
    <?php endif; ?>
    <?php if ($ad->getCity()) : ?>
    <strong>Ville</strong> : <a href="https://maps.google.fr/?z=9&q=<?php
        echo htmlspecialchars($ad->getCountry().' '.$ad->getCity());
    ?>" title="Localiser sur Google Map"><?php echo $ad->getCity(); ?></a>
    <?php endif; ?>
    <?php if ($siteConfig->getOption("pro_visible")) : ?>
    <br />Annonce de <?php echo $ad->getProfessional()?'professionnel':'particulier.'; ?>
    <?php endif; ?>
    <br />
    <?php if ($ad->getUrgent()) : ?>
    <strong style="color: #FF8900;">urgent</strong>
    <?php endif; ?>
    <?php if ($ad->getThumbnailLink()) : ?>
    <br /><img src="<?php echo str_replace('/thumbs/', '/images/', $ad->getThumbnailLink()); ?>" alt=""
        style="max-width: 100%; overflow:hidden;" />
    <?php else : ?>
    <br />Pas de photo disponible.
    <?php endif; ?>
</div>
<?php
return ob_get_clean();