<form action="" method="post">
    <fieldset>
        <legend>Renvoyer toutes les alertes ?</legend>
        <p>
            En confirmant, vous recevrez toutes les annonces pour chaque alerte
            lors du prochain contrôle de nouvelle annonce.
        </p>
        <p>
            <input type="submit" value="Confirmer" style="font-weight: bold;" />
            | <a href="?mod=mail">Annuler</a>
        </p>
    </fieldset>
</form>
